version: '2'
services:
  http:
    build:
      context: .
      target: http
    container_name: gobase_http
    env_file:
      - .env
    environment:
      SERVICE_NAME: gobase_http
      DD_SERVICE: gobase_http
      KAFAK__BROKER: kafka:9092
      DD_AGENT_HOST: datadog
      AWS_ENDPOINT: http://localstack-main:4566
      HTTP_SERVER__DOC_HOST: http://localhost:60005
      TEST_URL_1: "http://echo-nginx-1"
      TEST_URL_2: "https://gobase_http2:8080/service/echo"
    ports:
      - 60005:8080
    networks:
      - mongo_mongodb
      - kafka_kafka
      - common
      - localstack_localstack
  http2:
    build:
      context: .
      target: http2
    container_name: gobase_http2
    env_file:
      - .env
    environment:
      SERVICE_NAME: gobase_http2
      DD_SERVICE: gobase_http2
      KAFAK__BROKER: kafka:9092
      DD_AGENT_HOST: datadog
      AWS_ENDPOINT: http://localstack-main:4566
      HTTP_SERVER__DOC_HOST: https://localhost:60006
      HTTP_SERVER__TLS_PUBLIC_KEY: /service/server.crt
      HTTP_SERVER__TLS_PRIVATE_KEY: /service/server.key
      TEST_URL_1: "http://echo-nginx-1"
      TEST_URL_2: "http://gobase_http:8080/service/echo"
    ports:
      - 60006:8080
    networks:
      - mongo_mongodb
      - kafka_kafka
      - common
      - localstack_localstack
  h2c:
    build:
      context: .
      target: h2c
    container_name: gobase_h2c
    env_file:
      - .env
    environment:
      SERVICE_NAME: gobase_h2c
      DD_SERVICE: gobase_h2c
      KAFAK__BROKER: kafka:9092
      DD_AGENT_HOST: datadog
      AWS_ENDPOINT: http://localstack-main:4566
      HTTP_SERVER__DOC_HOST: http://localhost:60007
      TEST_URL_1: "http://echo-nginx-1"
      TEST_URL_2: "http://gobase_http:8080/service/echo"
    ports:
      - 60007:8080
    networks:
      - mongo_mongodb
      - kafka_kafka
      - common
      - localstack_localstack
  kafka-client:
    build:
      context: .
      target: kafka
    deploy:
      mode: replicated
      replicas: 3
    env_file:
      - .env
    environment:
      SERVICE_NAME: gobase_kafka
      DD_SERVICE: gobase_kafka
      KAFAK__BROKER: kafka:9092
      DD_AGENT_HOST: datadog
      AWS_ENDPOINT: http://localstack-main:4566
      TEST_URL_1: "http://echo-nginx-1"
      TEST_URL_2: "http://gobase_http:8080/service/echo"
    networks:
      - mongo_mongodb
      - kafka_kafka
      - common
      - localstack_localstack
  csfle:
    build:
      context: .
      target: httpcsfle
    env_file:
      - .env
    environment:
      KMS_PROVIDER: local
      SERVICE_NAME: gobase_csfle
      DD_SERVICE: gobase_csfle
      KAFAK__BROKER: kafka:9092
      DD_AGENT_HOST: datadog
      AWS_ENDPOINT: http://localstack-main:4566
      TEST_URL_1: "http://echo-nginx-1"
      TEST_URL_2: "http://gobase_http:8080/service/echo"
      CSFLE_CRYPT_SHARED_LIB_PATH: /service/pkg/mongo_crypt_shared_v1-7.0.5/lib/mongo_crypt_v1.so
    ports:
      - 60008:8080
    networks:
      - mongo_mongodb
      - kafka_kafka
      - common
      - localstack_localstack
networks:
  mongo_mongodb:
    external: true
  kafka_kafka:
    external: true
  common:
    external: true
  localstack_localstack:
    external: true
  