version: "3.9"
services:
  golang:
    image: "sabariram/golanglambdatest:latest"
    volumes:
      - .:/goserverbase
    networks:
      - mysqlnet
      - mongonet
      - graylog_graylog
    environment:
      MYSQL_HOST: localmysql
      MYSQL_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USERNAME: ${MYSQL_ROOT_USERNAME}
      MYSQL_PORT: 60002
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      GRAYLOG_ADD: graylog
      MONGO_URL: mongodb://localmongo:60001
      SERVICE_NAME: ${APP_SERVICE_NAME}
      LOG_LEVEL: ${LOG_LEVEL}
      AWS_REGION: ${AWS_REGION}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      KMS_ARN: ${KMS_ARN}
      SECRET_ARN: ${SECRET_ARN}
      SQS_URL: ${SQS_URL}
      FIFO_SQS_URL: ${FIFO_SQS_URL}
      SNS_ARN: ${SNS_ARN}
      GRAYLOG_PORT: ${GRAYLOG_PORT}
      LOG_BUFFER_SIZE: ${LOG_BUFFER_SIZE}
      S3_BUCKET: ${S3_BUCKET}
    command: tail -f /dev/null
    depends_on:
      - localmysql
      - localmongo
  localmysql:
    image: "mysql:8.0.28"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - 60002:3306/tcp
      - 60003:33060/tcp
    networks:
      - mysqlnet
    volumes:
      - /home/sabariram/Projects/DBData/GoBaseServer/MySQL:/var/lib/mysql
  localmongo:
    image: mongo:5.0.6
    ports:
      - 60001:27017/tcp
    networks:
      - mongonet
    volumes:
      - /home/sabariram/Projects/DBData/GoBaseServer/Mongo:/data/db
networks:
  mysqlnet: {}
  mongonet: {}
  graylog_graylog:
    external: true
