version: '2'
services:
  http:
    build:
      context: .
      target: http
    container_name: gobase_http
    env_file:
      - .env
    environment:
      SERVICE_NAME: gobase_http
      DD_SERVICE: gobase_http
      KAFKA_BROKER: broker:29092
      DD_AGENT_HOST: dreamy_cannon:8126
      DOC_HOST: http://localhost:60005
    ports:
      - 60005:8080
    networks:
      - mongo_mongodb
      - kafka_default
      - common
  http2:
    build:
      context: .
      target: http2
    container_name: gobase_http2
    env_file:
      - .env
    environment:
      SERVICE_NAME: gobase_http2
      DD_SERVICE: gobase_http2
      KAFKA_BROKER: broker:29092
      DD_AGENT_HOST: dreamy_cannon:8126
      DOC_HOST: https://localhost:60006
      HTTP2_PUBLIC_KEY: /app/server.crt
      HTTP2_PRIVATE_KEY: /app/server.key
    ports:
      - 60006:8080
    networks:
      - mongo_mongodb
      - kafka_default
      - common
  kafka:
    build:
      context: .
      target: kafka
    container_name: gobase_kafka
    env_file:
      - .env
    environment:
      SERVICE_NAME: gobase_kafka
      DD_SERVICE: gobase_kafka
      KAFKA_BROKER: broker:29092
      DD_AGENT_HOST: dreamy_cannon:8126
      KAFKA_CONSUMER_ID: gobase-test-docker-consumer
      KAFKA_TEST_TOPIC: com.oneapp.lending.uat.error
      KAFKA_TEST_TOPIC_2: com.oneapp.utility.uat.error
    networks:
      - mongo_mongodb
      - kafka_default
      - common
networks:
  mongo_mongodb:
    external: true
  kafka_default:
    external: true
  common:
    external: true