version: '2'
services:
  http:
    build:
      context: .
      target: http
    container_name: gobase_http
    env_file:
      - .env
    environment:
      SERVICE_NAME: gobase_http
      DD_SERVICE: gobase_http
      KAFKA_BROKER: broker:9092
      DD_AGENT_HOST: dreamy_cannon:8126
    ports:
      - 60005:8080
    networks:
      - mongo_mongodb
      - kafka_default
      - common
  http2:
    build:
      context: .
      target: http2
    container_name: gobase_http2
    env_file:
      - .env
    environment:
      SERVICE_NAME: gobase_http2
      DD_SERVICE: gobase_http2
      KAFKA_BROKER: broker:9092
      DD_AGENT_HOST: dreamy_cannon:8126
    ports:
      - 60006:8080
    networks:
      - mongo_mongodb
      - kafka_default
      - common
  kafka:
    build:
      context: .
      target: kafka
    container_name: gobase_kafka
    env_file:
      - .env
    environment:
      SERVICE_NAME: gobase_kafka
      DD_SERVICE: gobase_kafka
      KAFKA_BROKER: broker:9092
      DD_AGENT_HOST: dreamy_cannon:8126
    networks:
      - mongo_mongodb
      - kafka_default
      - common
networks:
  mongo_mongodb:
    external: true
  kafka_default:
    external: true
  common:
    external: true